### PR TITLE
Cpp benchmark - asio standalone

### PR DESCRIPTION
**Pull request by kassane**
No guarantee it's the best implementation or anything like that (I'm not expert in concurrent programming). However, another alternative for a library that is popular with C++ programmers is missing.

### CODE REVIEW

File: benchmarks/cpp/src/qsort.cpp [hunk 1]
```diff
@@ -0,0 +1,84 @@
...
+            }
+            if (left < right)
+            {
+                std::swap(vec[left], vec[right]);
+            }
+        }
+        std::swap(vec[pivot], vec[right]);
+        int pivot_point = right;
+        quicksort(vec, low, pivot_point - 1);
+        quicksort(vec, pivot_point + 1, high);
```
Comment (kprotty) [inline benchmarks/cpp/src/qsort.cpp]: The quicksort isn't executed concurrently, so this isn't a fair comparison of ASIO vs the other thread pool variants.

Comment (kassane) [reply benchmarks/cpp/src/qsort.cpp]: Sorry, what do you suggest to fix this?

Comment (kprotty) [reply benchmarks/cpp/src/qsort.cpp]: Im not too familiar with ASIO, but it should schedule at least one of the quicksort's concurrently to the other and wait for both to complete. The golang example showcases this more clearly: https://github.com/kprotty/zap/blob/blog/benchmarks/go/qsort.go#L58-L68

Comment (kassane) [reply benchmarks/cpp/src/qsort.cpp]: OK. I'll review the quicksort implementation.

**Comment by kassane** [comment]
@kprotty, follow your implementation suggestion based on some examples found in the asio source.

Although it was a leap for me!

File: benchmarks/cpp/build.zig [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+    }
+
+    const run_step = b.step("run", "Run the app");
+    run_step.dependOn(&run_cmd.step);
+    const git_step = b.step("git", "Run git clone asio");
+    git_step.dependOn(&asio.step);
+}
+
+fn gitClone(b: *std.build.Builder) *std.build.RunStep {
+    return b.addSystemCommand(&[_][]const u8{ "git", "clone", "https://github.com/chriskohlhoff/asio", "vendor/asio" });
```
Comment (kprotty) [inline benchmarks/cpp/build.zig]: Could this be a submodule instead?

File: benchmarks/cpp/src/qsort.cpp [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+    shuffle(begin(arr), end(arr), rng);
+}
+
+void quickSort(vector<int>& arr) {
+    if (arr.size() <= 32) {
+        insertionSort(arr);
+    } else {
+        io_context ctx;
+        steady_timer timer{ctx};
+        vector<int> arr1, arr2;
```
Comment (kprotty) [inline benchmarks/cpp/src/qsort.cpp]: These seem like they could remove by having quickSort() take in a start and end along with `arr`. Avoids heap allocating 2 intermediate vectors and copying them back at the end

File: benchmarks/cpp/src/qsort.cpp [hunk 4]
```diff
@@ -0,0 +1,79 @@
...
+#include <array>
+#include <asio.hpp>
+#include <chrono>
+#include <iostream>
+#include <random>
+#include <vector>
+
+using namespace asio;
+using namespace std;
+using namespace std::chrono;
```
Comment (kprotty) [inline benchmarks/cpp/src/qsort.cpp]: Could the functions/namespaces being used be qualified instead of brought into scope like this? I'm having a bit of issue figuring out where `async` and `launch::async` come from and how `ctx.run()` is connected to them to wait for the tasks to complete.

File: benchmarks/cpp/build.zig (hunk 2 above)
Comment (kassane) [reply benchmarks/cpp/build.zig]: No problem to add submodule? Ok!

File: benchmarks/cpp/src/qsort.cpp (hunk 3 above)
Comment (kassane) [reply benchmarks/cpp/src/qsort.cpp]: Iterator's... then need +1 param (begin and end) on quicksort and partitions. (maybe!!)

File: benchmarks/cpp/src/qsort.cpp (hunk 4 above)
Comment (kassane) [reply benchmarks/cpp/src/qsort.cpp]: `std::launch::async` force the asynchronous operation while the asio loop event with steady_timer making the function awaitable on each call. ctx.run (is blocking - threadsafe).

Ref:
https://think-async.com/Asio/asio-1.24.0/doc/asio/reference/io_context.html#asio.reference.io_context.synchronous_and_asynchronous_operations

**Comment by kassane** [comment]
@kprotty,

I recognize that asio has more sophisticated features that perhaps lean towards your experiment as an example: `asio:: awaitable<T>` (C++20) std coroutines enhanced.
So far I've had a lot of difficulty using it due to the need for some esoteric cxxflags from the library. (e.g.: `-DASIO_HAS_CO_AWAIT`).

Example:
https://github.com/chriskohlhoff/asio/blob/master/asio/src/examples/cpp20/channels/throttling_proxy.cpp

File: benchmarks/cpp/src/qsort.cpp (hunk 4 above)
Comment (kprotty) [reply benchmarks/cpp/src/qsort.cpp]: From the link, it looks like you should have an io_context passed to all quickSorts which is posted() to for spawning subsequent quickSorts, with a context.run() at main

File: benchmarks/cpp/src/qsort.cpp (hunk 3 above)
Comment (kassane) [reply benchmarks/cpp/src/qsort.cpp]: I tried to replace it with std::array, but I got segfault during execution!

File: benchmarks/cpp/src/qsort.cpp (hunk 4 above)
Comment (kassane) [reply benchmarks/cpp/src/qsort.cpp]: Putting `ctx.run` in main would crash and probably still require release or reset `ctx.reset` before re-running on each call.

File: benchmarks/cpp/src/qsort.cpp (hunk 3 above)
Comment (kprotty) [reply benchmarks/cpp/src/qsort.cpp]: I dont mean to replace the intermediary vectors with arrays, but to remove them in favor of slices:
```
qsort(vec, start, end):
  if (end - start) <= 32:
    return isort(vec, start, end)
  pivot = partition(vec, start, end)
  dispatch(qsort, vec, start, start + pivot)
  dispatch(qsort, vec, start + pivot, end)
  run()
```

Comment (kassane) [reply benchmarks/cpp/src/qsort.cpp]: I have made the suggested changes, but an unexpected error occurs in running step.
```c++
void quickSort(std::vector<int>& arr, int start, int end) {
    if (end - start <= 32) {
        insertionSort(arr, start, end); //custom insertionSort changed too
    } else {
        asio::io_context ctx;
        asio::steady_timer timer{ctx};

        const auto pivot = partition(arr, start, end); // custom partition changed too
        
        // Create a strand to wrap the async calls to quickSort
        asio::io_context::strand strand{ctx};
        auto quickSortWrapper = [&](auto&& arr, auto start, auto end) {
            quickSort(arr, start, end);
        };
        
        // Use the strand to dispatch the async calls to quickSort
        strand.dispatch(std::bind(quickSortWrapper, std::ref(arr), start, start + pivot));
        strand.dispatch(std::bind(quickSortWrapper, std::ref(arr), start + pivot, end));
        
        // Run the io_context to process the dispatched tasks
        ctx.run();
    }
}
```
**output:**
```bash
filling
shuffling
running
The following command terminated unexpectedly:
```

Comment (kprotty) [reply benchmarks/cpp/src/qsort.cpp]: try printing out the start & end of each invocation. It may not be handling negative sizes (end > start)

Comment (kassane) [reply benchmarks/cpp/src/qsort.cpp]: **output**

```bash
filling
shuffling
running
[...] // skip to final list
14 - 740
14 - 753
14 - 766
14 - 779
14 - 792
14 - 805
14 - 685
14 - 698
The following command terminated unexpectedly:
```

Comment (kassane) [reply benchmarks/cpp/src/qsort.cpp]: I will commit the change!

**Comment by kassane** [comment]
I can't say if it's considerable in terms of performance and tradeoffs.
Although it instigates to favor the library itself.
https://github.com/netcan/asyncio/blob/master/docs/benchmark.md

File: benchmarks/cpp/src/qsort.cpp (hunk 4 above)
Comment (kprotty) [reply benchmarks/cpp/src/qsort.cpp]: Why? ctx.run() should invoke the  quicksorts, which should dispatch/queue moer, which should runs those, until all quicksorts completes.

Comment (kassane) [reply benchmarks/cpp/src/qsort.cpp]: The problem at the moment from what I analyzed hangs during the call of the qsort function passing `ctx` (recursively).

So having the local context could be instantiated only after calling the reference lambda functions.

Comment (kassane) [reply benchmarks/cpp/src/qsort.cpp]: I understand it this way:

**Local context:**

```
qsort(...):
   ctx
   lambda(qsort):
      ctx.run
   dispatch1(lambda) //ctx (run/stop)
   dispatch2(lambda) //ctx (run/stop)

    ctx.run/stop // will hold until it exits the operation.
```
**Main context:**

```
qsort(...,ctx):
   lambda(qsort(arr, ctx)):
   dispatch1(lambda)
   dispatch2(lambda)
main():
   qsort (...,ctx)
    ctx.run
   // recursive reference will crash the ctx (no run/stop)
```

Comment (kassane) [reply benchmarks/cpp/src/qsort.cpp]: Fixed: conceptual context.

**Comment by kassane** [comment]
@kprotty,

(`std::async` + `std::deque`)
I'm looking into this solution, maybe it can help.
https://github.com/akselsd/AsyncQuicksort/blob/master/quicksort.hpp#L64-L97

File: benchmarks/cpp/src/qsort.cpp (hunk 4 above)
Comment (kprotty) [reply benchmarks/cpp/src/qsort.cpp]: Under main-context, what does it mean that recursive context crashes the ctx?

Comment (kassane) [reply benchmarks/cpp/src/qsort.cpp]: When executing after the qsort operation, the referenced ctx will simply not execute in the recursion.
Perhaps I would need to add a threadpool to instantiate the main context together with qsort.

If you execute the main context before to call qsort, the execution state will not be shared.

Comment (kprotty) [reply benchmarks/cpp/src/qsort.cpp]: I was thinking it runs like this:
```
main:
  qsort(0, 4):
    enqueue(qsort, 0, 2)
    enqueue(qsort, 2, 4)
  ctx.run():
    dequeue qsort(0, 2):
      enqueue(qsort, 0, 1)
      enqueue(qsprt, 1, 2)
    dequeue qsort(2, 4):
      enqueue(qsort, 2, 3)
      enqueue(qsort, 3, 4)
    dequeue(qsorts (0, 1), (1, 2), (2, 3), (3, 4))
    empty so stop
```

Comment (kassane) [reply benchmarks/cpp/src/qsort.cpp]: Not work (deadlock)

Comment (kassane) [reply benchmarks/cpp/src/qsort.cpp]: @kprotty , new commit w/ `ctx.run` on `main()`.

File: benchmarks/cpp/src/qsort.cpp [hunk 5]
```diff
@@ -0,0 +1,73 @@
...
+}
+
+awaitable<void> quickSort(asio::io_context& ctx, std::vector<int>& arr, unsigned long start, unsigned long end) noexcept {
+    if (end - start <= 32) {
+        insertionSort(arr, start, end);
+        co_return;
+    }
+
+    const auto pivot = partition(arr, start, end);
+    co_await quickSort(ctx, arr, start, start + pivot);
```
Comment (kprotty) [inline benchmarks/cpp/src/qsort.cpp]: This looks like it should be `co_spawn()` for it to run concurrently to the quickSort() after it. Otherwise, it converges into a normal/synchronously quickSort() impl.

File: benchmarks/cpp/src/qsort.cpp [hunk 6]
```diff
@@ -0,0 +1,73 @@
...
+    std::cout << "shuffling" << std::endl;
+    shuffle(arr);
+
+    std::cout << "running" << std::endl;
+    const auto start = high_resolution_clock::now();
+    asio::io_context ctx;
+    co_spawn(ctx, [&]() -> awaitable<void> {
+        co_await quickSort(ctx, arr, 0, arr.size());
+    }, detached);
+    ctx.run();
```
Comment (kprotty) [inline benchmarks/cpp/src/qsort.cpp]: Neat. Is there a way to make the io_context now use multiple threads since scheduling is fixed? Not sure if it does so by default.

**Review by kprotty — COMMENTED** [review]
Nice use of C++20 coroutine stuff

File: benchmarks/cpp/src/qsort.cpp (hunk 6 above)
Comment (kassane) [reply benchmarks/cpp/src/qsort.cpp]: [`asio::thread_pool`](https://think-async.com/Asio/asio-1.24.0/doc/asio/reference/thread_pool.html)

File: benchmarks/cpp/src/qsort.cpp (hunk 5 above)
Comment (kassane) [reply benchmarks/cpp/src/qsort.cpp]: `asio::co_spawn` is a function that creates a new fiber to execute a function concurrently with the current fiber. It returns an awaitable object that can be awaited to wait for the new fiber to complete.

File: benchmarks/cpp/src/qsort.cpp (hunk 6 above)
Comment (kassane) [reply benchmarks/cpp/src/qsort.cpp]: I believe that using a thread pool to execute the recursive calls to quickSort instead of fibers may result in slower execution because of the overhead of creating and managing threads.
But, I am still struggling quite a bit here about.... Studying about `asio` is not easy at all (esoteric lib)!

Comment (kassane) [reply benchmarks/cpp/src/qsort.cpp]: I'ts possible add threads on context: `asio::io_context ctx{N};` to N threads!

Comment (kassane) [reply benchmarks/cpp/src/qsort.cpp]: Also, I have tried to use thread pooling, but an error occurs when the array is not sorted.
```c++
// main function, after declaring ctx;
asio::thread_pool pool{4}; // specify the number of threads to use
    asio::io_context::work work{ctx}; // keep the io_context running until stopped
    co_spawn(pool, [&]() -> awaitable<void> {
        co_await quickSort(ctx, arr, 0, arr.size());
    }, detached);
    ctx.run();
    pool.join();
``

**Comment by kassane** [comment]
@kprotty , my last commit ~~fix:~~

```bash
filling
shuffling
running
Values before co_await: 0 - 10000000
took 929ms
```

Edit

the change only uses `insertSort` or `std::sort`.

File: benchmarks/cpp/src/qsort.cpp (hunk 6 above)
Comment (kprotty) [reply benchmarks/cpp/src/qsort.cpp]: The array not being sorted means that it's not waiting for all spawned quickSorts correctly. Would have to see how quickSort() does the co_spawn (it should use pool, and youd probably need a way to synchronize shutdown of it).

>  using a thread pool to execute the recursive calls to quickSort instead of fibers may result in slower execution because of the overhead of creating and managing threads.

Thread-pools are meant to spawn threads and keep them alive, supposedly amortizing the cost of creating/managing them. These benchmarks are specifically made to put strain on their runtime's thread-pools as that overhead is what is being measured/compared. (There are definitely faster ways to write a parallel quicksort than those in this repo; The rust `rayon::join` version employs those optimizations and I had to use one of its APIs that doesn't to keep what it's comparing fair)

Comment (kassane) [reply benchmarks/cpp/src/qsort.cpp]: Indeed.

File: benchmarks/cpp/src/qsort.cpp (hunk 5 above)
Comment (kprotty) [reply benchmarks/cpp/src/qsort.cpp]: yea, so it should be something like this to allow the other half to run concurrently:
```cpp
auto fiber = co_spawn(ctx/pool, qsort, start, start + pivot)
co_await qsort(start + pivot, end)
co_await fiber;
```

Comment (kassane) [reply benchmarks/cpp/src/qsort.cpp]: > 
> ```c++
> auto fiber = co_spawn(ctx/pool, qsort, start, start + pivot)
> co_await qsort(start + pivot, end)
> co_await fiber;
> ```

It would not work, because `qsort` is void type. `co_spawn` generates an error by not returning any value and it also allows only 4 arguments, in which case it would be 7.
```
co_spawn.hpp:386:1: note: candidate function not viable: requires at most 4 arguments, but 7 were provided
```
For this reason the ideal use lambda!

Comment (kprotty) [reply benchmarks/cpp/src/qsort.cpp]: I was using pseudo-code, also qsort returns an awaitable instead of void so it should work no?

Comment (kassane) [reply benchmarks/cpp/src/qsort.cpp]: Unfortunately it didn't work here in the tests.
Still researching the overhead involved with `co_spawn`. However, some implicit changes in the asio code after version 1.20 make this difficult.

**Comment by kassane** [comment]
@kprotty ,

new commit - Refactored code!!!

```
filling
shuffling
running
took 1494ms
```

**Comment by kassane** [comment]
The new refactored version of c++20 coroutines works, slightly faster than strand.

**Comment by kassane** [comment]
@kprotty,

I think that the rabbit hole is currently emerging. Would it be valid to optimize further after this new refactoring?
I've tried to avoid using as much of the complexity of TMP (template metaprogramming) as possible!

File: benchmarks/cpp/src/coro-qsort.cpp [hunk 7]
```diff
@@ -0,0 +1,72 @@
...
+    auto pivot = begin + std::distance(begin, end) - 1;
+    auto i = std::partition(begin, pivot, [=](int x){ return x <= *pivot; });
+    std::swap(*i, *pivot);
+
+    auto quickSortWrapper = [&](auto &&begin, auto &&end) {
+      quickSort(ctx, begin, end);
+    };
+
+    co_await quickSort(ctx, begin, i);
+    co_await quickSort(ctx, i + 1, end);
```
Comment (kprotty) [inline benchmarks/cpp/src/coro-qsort.cpp:25]: These parts still need to be done concurrently to each other, otherwise this is a synchronous quickSort(). From [this post](https://cppalliance.org/richard/2021/05/30/RichardsMayUpdate.html) it looks like you can create an awaitable handle to co_spawn, so:
```cpp
auto left = co_spawn(ctx, [&]() -> quickSort(ctx, begin, i), aio::use_awaitable);
auto right = co_spawn(ctx, [&]() -> quickSort(ctx, i + 1, end), aio::use_awaitable);
co_await left;
co_await right;
co_return;
```

Comment (kassane) [reply benchmarks/cpp/src/coro-qsort.cpp:25]: don't work with latest version 1.24.

And by readjusting:
```c++
auto left = co_spawn(ctx, quickSort(ctx, begin, i), asio::use_awaitable);
    auto right = co_spawn(ctx, quickSort(ctx, i + 1, end), asio::use_awaitable);

    co_await left; // Error: call deleted awaitable
    co_await right;
    co_return;
```
**output:**

```bash
error(compilation): clang failed with stderr: /home/kassane/Documentos/Projetos/zap/benchmarks/cpp/src/coro-qsort.cpp:32:14: error: call to deleted constructor of 'awaitable<void, asio::any_io_executor>'
```

Comment (kassane) [reply benchmarks/cpp/src/coro-qsort.cpp:25]: Works:

```c++
co_await co_spawn(ctx, quickSort(ctx, begin, i), asio::use_awaitable);
co_await co_spawn(ctx, quickSort(ctx, i + 1, end), asio::use_awaitable);

    // co_await left;
    // co_await right;
    co_return;
```
running
took 3024ms

**Comment by kassane** [comment]
Hi @madmongo1,

First, I apologize for mentioning it without contacting you previously.

We are trying to get the best "possible" solution in an asynchronous qsort. I don't have much experience in using coroutines nor asio standalone coroutines.

Based on current solution which returns ±1230ms (coro-qsort).

In the last Review it is noticed that `co_spawn` receives an awaitable function that is immediately destroyed. That would happen on every call, right?

Note: Development environment would be equivalent to (`zig c++` = `clang with libc++`).

File: benchmarks/cpp/src/coro-qsort.cpp (hunk 7 above)
Comment (kprotty) [reply benchmarks/cpp/src/coro-qsort.cpp:25]: Hm, the issue is `co_await`ing the first recursion which makes it a dependency of the second and prohibits running them concurrently. Any scheme that does this is effectively a slower synchronous version. Is there a way to get around this?

Comment (kassane) [reply benchmarks/cpp/src/coro-qsort.cpp:25]: I did some tests that did not work significantly.
Including the change below to try to stop the counting error from breaking the operation by throwing an exception.
```c++
co_spawn(ctx, quickSort(ctx, begin, i), asio::use_awaitable); // emit exception - no sort array
// co_spawn(ctx, quickSort(ctx, begin, i), asio::use_future); // no error (took 2742ms)
co_await quickSort(ctx, i + 1, end);
```
I also removed the `co_await` from `co_spawn` in main function. Not much difference in the result, except that if you use `use_awaitable` it also throws an exception.

Comment (kassane) [reply benchmarks/cpp/src/coro-qsort.cpp:25]: use_awaitable is lazy with any operations, so it'll only make progress once you co_await it.

Comment (kassane) [reply benchmarks/cpp/src/coro-qsort.cpp:25]: @kprotty, with the new parallel (w/`use_future`) example. I still (maybe) need to readjust about it.

```bash
filling
shuffling
running
took 319ms
```
But the qsort example itself for c++ will include even more overhead.
Perhaps I would need to redefine the example in C++ for all corresponding examples.

Comment (kassane) [reply benchmarks/cpp/src/coro-qsort.cpp:25]: I found information about what happens in co_spawn.

>"Make sure you never use reference capturing lambdas which are coroutines. The first time they suspend the lambda object gets destroyed. I find myself almost always writing reference capturing lambdas, so I ended up writing some C++ 20 type constraints which stop the compiler from letting me write reference capturing coroutine lambdas (just compare their sizeof to one) and now I'm good." [14ned - Reddit](https://www.reddit.com/r/cpp/comments/u3igrf/comment/i4qdsxw/)
